In [4]:
import torch
import torch.nn as nn

In [13]:
torch.manual_seed(42)

X = torch.tensor(
    [1.0, 2.0, 3.0],
)
X

tensor([1., 2., 3.])

In [14]:
neuron = nn.Linear(
    in_features=3,
    out_features=1
)

In [15]:
y = neuron(X)

In [16]:
y

tensor([1.5244], grad_fn=<ViewBackward0>)

In [17]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [18]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)